#!/usr/bin/env python

import pygtk
pygtk.require('2.0')
import gtk
import os

class MyWindow(gtk.Window):
	def __init__(self):
		
		gtk.Window.__init__(self)
		self.set_title(" ")
		self.set_size_request(700, 400)
		
		self.mainbox = gtk.VBox(spacing=6)
		self.add(self.mainbox)
		
		infinity_img = gtk.Image()
		pixbuf = gtk.gdk.pixbuf_new_from_file("/opt/infinity/infinity-icon.png")
		#sbuf = pixbuf.scale_simple(100,100,gtk.gdk.INTERP_BILINEAR)
		sbuf = pixbuf;
		infinity_img.set_from_pixbuf(sbuf)
		self.set_icon(sbuf)
		self.mainbox.pack_start(infinity_img)
		
		self.infolabel = gtk.Label()
		self.infolabel.set_markup("<span size='23000'>infinity</span>")
		self.mainbox.pack_start(self.infolabel)
		
		self.textlabel = gtk.Label();
		self.textlabel.set_label("An update for infinity is available. To install it you will need admin privileges");
		self.mainbox.pack_start(self.textlabel);
		
		self.btn = gtk.Button(label="Update")
		self.btn.connect("clicked", self.btn_clicked)
		self.btn.set_size_request(300, 70)
		self.mainbox.pack_start(self.btn)
		
	def btn_clicked(self, widget):
		os.system("rm /tmp/infinity-update");
		os.system("wget https://github.com/dari-ta/bunsen-infinity/archive/master.zip -P /tmp/infinity-update/");
		os.system("unzip /tmp/infinity-update/master.zip -d /tmp/infinity-update/");
		os.system("gksudo /tmp/infinity-update/bunsen-infinity-master/opt/infinity/install.sh");
		gtk.main_quit()
		
win = MyWindow()
win.connect("delete-event", gtk.main_quit)
win.show_all()
gtk.main()
